### ISSUE TITLE
Дочистить реализацию вектора

### ISSUE THREAD

**Issue by avasyukov** [IvanOfficial/Vector2_and_Matrix2#1]
По сути - почти. По технике реализации нужно поправить два момента:

1. Не хранить данные в public

2. Убедиться, что успешно компилится вот такой main:
```c++
int main()
{
    std::cout << "=== Test vector ===" << std::endl;

    Vector2D v1 = {1, 1};
    Vector2D v2 = {2, 2};

    std::cout << (v1 + v2) << std::endl;
    std::cout << (v1 - v2) << std::endl;
    std::cout << v1 * 5 << std::endl;
    std::cout << -5 * v2 << std::endl;
    std::cout << v1 << std::endl;
    std::cout << v2 << std::endl;

    std::cout << v1 * v2 << std::endl;

    return 0;
}
```

**Comment by avasyukov** [comment]
Ревью вектора после обновления кода:

**1. Убрать** #ifndef / #define / #endif - в файле с реализацией они не нужны.

**2. Убедиться**, что данный main таки компилится. Вопрос сейчас не в версиях стандарта языка. Если компилятор не умеет в c++11 - ок, достаточно заменить
```c++
    Vector2D v1 = {1, 1};
    Vector2D v2 = {2, 2};
```
на
```c++
    Vector2D v1(1, 1);
    Vector2D v2(2, 2);
```
Но весь остальной код должен работать.

Сейчас не работает, выдавая стену ошибок. (Хинт - не хватает буквально одного штриха в сигнатурах методов.)

**3. (Раз уж сдаёмся на отл) Устранить** дублирование кода. Реализуйте друг через друга операторы:
- == и !=
- умножение на скаляр для разного порядка параметров

Этот фэн-шуй уместен, так как:
- разные методы становятся правда разными логическими, код становится резко легче читать (не нужно мучительно гадать, два метода это копи-паста друг друга, или там где-то в силу чего-то какой-нибудь индекс отличается)
- становится резко легче рефакторить код (через условный год) - правим одну точку кода, все логически связанные правятся автоматически

**Comment by avasyukov** [comment]
Вы выкрутились очень неожиданным для меня образом. Тикет засчитываем и закрываем.

Но вообще ожидалось, что оператор вместо
```c++
Matrix2 operator* (const int a);
```
станет
```c++
Matrix2 operator* (const int a) const;
```
Второй const (после параметров) логически означает "оператор не меняет состояние объекта, на которым вызван (поля внутри this)".

После этого можно написать просто
```c++
Matrix2 operator* (int a, const Matrix2& m)
{
        m * a;
}
```

**Comment by avasyukov** [comment]
Ну и чисто синтаксические ремарки для полноты картины и на будущее.

1. Вместо
```c++
bool Matrix2::operator== (const Matrix2& v2)
{
        if((this->x == v2.getX()) && (this->y == v2.getY()) && (this->z == v2.getZ()) && (this->s == v2.getS()))
        {
                return true;
        }
        else
        {
                return false;
        }
}
```
заметно более изящно и читаемо будет
```c++
bool Matrix2::operator== (const Matrix2& v2)
{
        return x == v2.getX() && y == v2.getY() && z == v2.getZ() && s == v2.getS();
}
```
или даже 
```c++
bool Matrix2::operator== (const Matrix2& v2)
{
        return x == v2.x && y == v2.y && z == v2.z && s == v2.s;
}
```
(последний вариант возможен, так как оба операнда типа Matrix2, так что есть доступ к private полям второго аргумента).

2. Вместо
```c++
bool Matrix2::operator!= (const Matrix2& v2)
{
    return !(this->operator ==(v2));
}
```
я бы написал
```c++
bool Matrix2::operator!= (const Matrix2& v2)
{
    return !(*this == v2);
}
```

**Comment by avasyukov** [comment]
Осталось убрать статики. Они потенциально откроют портал в ад, если тестировать сильно глубже.

**Comment by GerasimovIV** [comment]
да, точно, я про класс вектор совсем забыл. Сделал по аналогии с матрицами.

**Comment by avasyukov** [comment]
Доделано. Ура.
