### ISSUE TITLE
Дочистить реализацию матрицы

### ISSUE THREAD

**Issue by avasyukov** [IvanOfficial/Vector2_and_Matrix2#2]
По сути - почти. По технике реализации нужно поправить два момента:

1. Не хранить данные в public

2. Убедиться, что успешно компилится вот такой main:
```c++
int main()
{
    Matrix2 m1(0, 1, 1, 2);
    Matrix2 m2(0, 1, 2, 2);

    std::cout << "=== Test matrix ===" << std::endl;

    std::cout << (m1 + m2) << std::endl;
    std::cout << (m1 - m2) << std::endl;
    std::cout << m1 * 5 << std::endl;
    std::cout << -5 * m2 << std::endl;
    std::cout << m1 << std::endl;
    std::cout << m2 << std::endl;
    std::cout << m1 * m2 << std::endl;
    std::cout << m1.det() << std::endl;

    std::cout << "=== Cross test vector and matrix ===" << std::endl;

    Vector2D v1 = {1, 1};
    std::cout << m1 * v1 << std::endl;

    return 0;
}
```

**Comment by GerasimovIV** [comment]
дочистил реализации матрицы и вектора, но все работает под стандартами с++11

**Comment by avasyukov** [comment]
Ревью матрицы после обновления кода:

**1. Дочистить перегрузку <<** - это вот здесь:
https://github.com/IvanOfficial/Vector2_and_Matrix2/blob/90a8950e3c076a272c2a3dbb9daa0f56bd9002ed/Matrix.cpp#L171-L182
Нужно:
- не передавать копию матрицы, передавать референс
- реализацию для вектора снести, она есть в исходнике вектора

**2. Убедиться**, что main продолжит работать после правок п.1.

**3. (Раз уж сдаёмся на отл) Устранить** дублирование кода. Аналогично вектору. Реализуйте друг через друга операторы:
- == и !=
- умножение на скаляр для разного порядка параметров

**Comment by GerasimovIV** [comment]
окей. все сделал.
Единственное не понял про умножение на скаляр для разного порядка параметров.
Через умножение на число что нужно реализовать?

**Comment by avasyukov** [comment]
Сейчас есть умножение матрицы на скаляр и скаляра на матрицу. И сейчас это два раза записанная одна и та же реализация. Нужно, чтобы один из операторов свёлся к вызову другого оператора. Примерно как == и !=.

Понятно, что в данном случае 2D-матрицы кода в операторе совсем копейки. Но это только потому, что задача так специально подобрана. Для более сложных классов и громоздких операторов это правда достаточно важно - см. ремарки про фэн-шуй в #1.

**Comment by GerasimovIV** [comment]
понял, сейчас сделаю

**Comment by GerasimovIV** [comment]
переделал

**Comment by GerasimovIV** [comment]
ААААА, все, дошло до меня!!! Я наконец понял, что в конце функции, если в ней вызывался конструктор, то вызывается деструктор! Просто очень странное поведение было у моего кода, я пытался бороться с эти при помощи static, хотя понимал, что это неправильно. Сейчас все осознал и исправил

**Comment by GerasimovIV** [comment]
внутри operator<< (Matrix2& const v) // const дописал
сейчас все окей, так как деструктор вызывается после return (внутри operator + например) и код не падает пока работает  operator<<

**Comment by GerasimovIV** [comment]
тем более что я зафиксировал ссылку

**Comment by avasyukov** [comment]
Осталось правда убрать static-и. И на этом будет всё.

**Comment by avasyukov** [comment]
Вы выкрутились очень неожиданным для меня образом. Тикет засчитываем и закрываем.

Но вообще ожидалось, что оператор вместо
```c++
Matrix2 operator* (const int a);
```
станет
```c++
Matrix2 operator* (const int a) const;
```
Второй const (после параметров) логически означает "оператор не меняет состояние объекта, на которым вызван (поля внутри this)".

После этого можно написать просто
```c++
Matrix2 operator* (int a, const Matrix2& m)
{
        m * a;
}
```

**Comment by avasyukov** [comment]
Ну и чисто синтаксические ремарки для полноты картины и на будущее.

1. Вместо
```c++
bool Matrix2::operator== (const Matrix2& v2)
{
        if((this->x == v2.getX()) && (this->y == v2.getY()) && (this->z == v2.getZ()) && (this->s == v2.getS()))
        {
                return true;
        }
        else
        {
                return false;
        }
}
```
заметно более изящно и читаемо будет
```c++
bool Matrix2::operator== (const Matrix2& v2)
{
        return x == v2.getX() && y == v2.getY() && z == v2.getZ() && s == v2.getS();
}
```
или даже 
```c++
bool Matrix2::operator== (const Matrix2& v2)
{
        return x == v2.x && y == v2.y && z == v2.z && s == v2.s;
}
```
(последний вариант возможен, так как оба операнда типа Matrix2, так что есть доступ к private полям второго аргумента).

2. Вместо
```c++
bool Matrix2::operator!= (const Matrix2& v2)
{
    return !(this->operator ==(v2));
}
```
я бы написал
```c++
bool Matrix2::operator!= (const Matrix2& v2)
{
    return !(*this == v2);
}
```
